name: mangadex
description: Mangadex flutter client
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^5.1.2
  retrofit: ^4.0.1
  get_it: ^7.6.0
  injectable: ^2.1.1
  json_annotation: ^4.8.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  auto_route: ^7.1.0
  smartstruct: ^1.4.0
  provider: ^6.0.5
  equatable: ^2.0.5
  reactive_forms: ^14.3.0
  url_launcher: ^6.1.11
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  # update to 3.0.2 when it's stable
  easy_localization: ^3.0.2-dev.6
  hexcolor: ^3.0.1
  pretty_dio_logger: ^1.3.1
  oauth2: ^2.0.1
  flutter_secure_storage: ^8.0.0
  easy_logger: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_lints: ^2.0.1
  retrofit_generator: ^7.0.0
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.2
  auto_route_generator: ^7.0.0
  smartstruct_generator: ^1.4.0
  import_sorter: ^4.6.0
  assets_gen: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/

import_sorter:
  ignored_files:
    - .+g.dart
    - .+gr.dart

assets_gen:
  output: infrastructure/mangadex_assets.dart
  gen_package_path: false
  code_style: lowerCamelCase
  with_file_extension_name: false
  exclude:
    - assets/translations/*