name: mangadex
description: Mangadex flutter client
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6
  dio: 5.4.0
  retrofit: 4.0.3
  get_it: 7.6.4
  injectable: 2.3.2
  json_annotation: 4.8.1
  bloc: 8.1.2
  flutter_bloc: 8.1.3
  auto_route: 7.8.4
  provider: 6.1.1
  equatable: 2.0.5
  reactive_forms: 16.1.1
  url_launcher: 6.2.2
  google_fonts: 6.1.0
  flutter_svg: 2.0.9
  easy_localization: 3.0.3
  hexcolor: 3.0.1
  pretty_dio_logger: 1.3.1
  flutter_secure_storage: 9.0.0
  easy_logger: 0.0.2
  collection: 1.18.0
  path: 1.9.0
  cached_network_image: 3.3.0
  isar:
  isar_flutter_libs:
  path_provider: 2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: 6.3.0
  build_runner:
  flutter_lints: 3.0.1
  retrofit_generator: 8.0.6
  injectable_generator: 2.4.1
  json_serializable: 6.7.1
  auto_route_generator: 7.3.2
  import_sorter: 4.6.0
  flutter_gen_runner:
  # Switch to pub when analyzer is updated to v6+
  isar_generator:
    git:
      url: https://github.com/ndelanou/isar.git
      path: packages/isar_generator
      ref: analyzer-v6

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/

import_sorter:
  ignored_files:
    - .+g.dart
    - .+gr.dart

flutter_gen:
  output: lib/infrastructure/

#  integrations:
#    flutter_svg: true

  assets:
    outputs:
      style: camel-case
    exclude: [assets/translations/*]

#  gen_package_path: false
#  code_style: lowerCamelCase
#  with_file_extension_name: false
#  exclude:
#    - assets/translations/*