// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 11.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'mangadex';

  static const String assetsBackIcon = 'assets/back-icon.svg';

  static const String assetsCloseIcon = 'assets/close-icon.svg';

  static const String assetsDropIcon = 'assets/drop-icon.svg';

  static const String assetsFavicon = 'assets/favicon.svg';

  static const String assetsGuestIcon = 'assets/guest-icon.svg';

  static const String assetsMangadexLogo = 'assets/mangadex-logo.svg';

  static const String assetsMangadexWordmark = 'assets/mangadex-wordmark.svg';

  static const String assetsMenuIcon = 'assets/menu-icon.svg';

  static const String assetsSearchIcon = 'assets/search-icon.svg';

  static const String assetsSettingsIcon = 'assets/settings-icon.svg';

  static const String assetsSignOutIcon = 'assets/sign-out-icon.svg';
}
